// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: unix-time.proto

package netty.sample.proto;

public interface UnixTimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnixTime)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   */
  int getValue();
}
